# Generated by Django 3.1.3 on 2020-12-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201203_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_move',
            name='ip',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
