# Generated by Django 3.1.3 on 2020-12-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_powermodel_studentmodel_userinformationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='UserModel',
        ),
    ]
