# Generated by Django 3.1.3 on 2020-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201204_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermodel',
            name='team',
            field=models.CharField(max_length=30, verbose_name='组别'),
        ),
    ]
